[package]
name = "noflipbookanim"
version = "0.1.0"
edition = "2021"

[lib]
name = "minecraft_flipbook"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"

[profile.release]
lto = true
strip = true

[profile.githubci]
inherits = "release"
lto = true
strip = true